### ISSUE TITLE
Add auto deletion code after successful upload

### ISSUE THREAD

**Issue by mjb-oz** [AirborneLogic/pospac-automation#1]

**Comment by mjb-oz** [comment]
I'd have this as an extra command line parameter eg def download_upload(gcs_path, delete_on_completion = False)

Need to remove all trace of it, so the local_address folder and all its contents need to disappear

**Comment by longhan-airborne** [comment]
30666fe2622cf2f98f9c0ffd3e5d6ca077ab7778

**Comment by longhan-airborne** [comment]
I tested the deletion function in three scenarios,  
In cmd input : python pospac.py url deletion run_label
if  deletion =True 
do delete

if deletion =False
do not delete

if input = python pospac.py url
default -> do not delete
